<tr class="row<%evenodd%>">
  <td style="background: <%player.teamcolor%>;">&nbsp;</td>
  <td><%player.name%></td>
  <td class="right"><%player.ranking%></td>
  <td class="right"><%player.score%></td>
  <td class="right"><%player.deaths%></td>
  <td class="right"><%player.kills%></td>
  <td class="right"><%player.ping%></td>
  <td class="center"><%player.bot%></td>
  <td class="center"><%player.admin%></td>
</tr>
